#!/bin/sh

set -ue

# This script builds all the Docker images. It is used by `test`, only extracted here for end user
# convenience. For example, [../README.md] mentions this file.

version=${1:-master}
if [ "${version}" != "master" ]; then
  export JAVA_VERSION=${version}
fi

export DOCKER_FILE=Dockerfile
DOCKER_TARGET=jdk build-bin/docker/docker_build openzipkin/java:test ${version}
DOCKER_TARGET=jre build-bin/docker/docker_build openzipkin/java:test-jre ${version}
