#!/bin/sh
#
# Copyright 2019-2020 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

set -ue

version=${1:-master}
if [ "${version}" != "master" ]; then
  export JAVA_VERSION=${version}
fi

export DOCKER_FILE=Dockerfile
DOCKER_TARGET=jdk build-bin/docker/docker_build openzipkin/java:test ${version}
DOCKER_TARGET=jre build-bin/docker/docker_build openzipkin/java:test-jre ${version}
