#!/bin/sh

set -ue

# This script runs the tests of the project.
#
# See [README.md] for an explanation of this and how CI should use it.

build-bin/build
docker run --rm openzipkin/java:test -version
docker run --rm openzipkin/java:test-jre -version
